# Generated by Django 4.0 on 2021-12-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_park_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
